name = "Tetratto"
description = "ğŸ tetratto!"
color = "#c9b1bc"
port = 4118

[security]
registration_enabled = true
admin_user = "admin"
real_ip_header = "CF-Connecting-IP"

[dirs]
templates = "html"
assets = "public"

[database]
name = "atto.db"
